[project]
name = "snake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arcade>=3.3.3",
    "google>=3.0.0",
    "protobuf>=6.33.2",
    "pyqt6>=6.10.0",
    "pyyaml>=6.0.3",
]
